### ISSUE TITLE
Re-useable workflows

### ISSUE THREAD

**Issue by JeffersonBledsoe** [plone/.github#1]
GitHub added support for re-useable workflows today in public beta. The [documentation on re-useable workflows](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#creating-a-reusable-workflow) is already available and it seems fairly straightforward to make an existing workflow one that could be reused.

**Comment by mauritsvanrees** [comment]
I am experimenting with a reusable workflow for running some [`buildout.coredev` tests](https://github.com/plone/.github/blob/main/.github/workflows/coredev-60.yml) on GitHub Actions. See https://github.com/plone/Products.CMFPlone/pull/3540 which uses it.

We will have to see if we want to go this route for coredev tests. But reusable workflows in themselves seem like a good idea. It would be good to change our current starter workflows to call reusable workflows. Then the workflows that are generated from the starters will be much smaller, and will remain up to date with current best practices. (I have not tried out the current starter workflows yet though.)

**Comment by gforcada** [comment]
We are already using them on `plone/meta` for quite some time 😄
